### ISSUE TITLE
Write README.md

### ISSUE THREAD

**Issue by hannahgooding** [fac19/week4-harl#5]
UPDATE README [HACKMD](https://hackmd.io/@r0g/rkClO6_IU)

**Comment by Lizzy-j** [comment]
Feedback from last week's project:

Your readme is good, it tells me about what you want to learn from the project but it doesn't explain what you actually have learned. You can possibly describe your journey to completion, what you have learned, what next (what you could have done with more time) and most importantly, how to run/check your tests.
